using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// COM interop identity remains stable; assembly metadata is generated by MSBuild.
[assembly: ComVisible(false)]
[assembly: Guid("c1b28428-5a33-4a00-b4d9-6e354457b442")]
[assembly: InternalsVisibleTo("ResearchReinvented.Tests")]
